name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Check Format
        id: format-check
        run: npm run format:check

      - name: Lint
        id: lint
        run: npm run lint

      - name: Test
        id: test
        run: npm run ci-test
