name: Continuous Delivery

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release Version
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'dependabot/') == false)

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-tags: true

      - name: Tag
        id: tag
        uses: issue-ops/semver@5b8bb084b6834d03ddb5c7c96c683a588a2072ca # v2
        with:
          manifest-path: package.json
          workspace: ${{ github.workspace }}
          ref: main

      - name: Create Release
        id: release
        uses: issue-ops/releaser@e6768024642153d17c157995e2684a3ebcae14e7 # v2
        with:
          tag: v${{ steps.tag.outputs.version }}
